# Generated by Django 4.1.7 on 2023-04-03 09:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0002_rename_drivers_dish_cooks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="cooks",
            field=models.ManyToManyField(
                related_name="models", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
